/******************************************************************************/
//
// This file was generated by OSAcfg_Tool utility.
// Do not modify it to prevent data loss on next editing.
//
// PROJECT NAME: Running lights
//
// PLATFORM:     mikroC for PIC16
//
/******************************************************************************/


#ifndef _OSACFG_H
#define _OSACFG_H

//------------------------------------------------------------------------------
// SYSTEM
//------------------------------------------------------------------------------

#define OS_TASKS                2  // Number of tasks that can be active at one time
#define OS_PRIORITY_LEVEL       OS_PRIORITY_EXTENDED        //
#define OS_ENABLE_CSEM
#define OS_CSEM_SIZE            1
#define OS_BSEMS                 1

 #define OS_STIMERS_ENABLE_ALLOCATION
 #define OS_STIMERS  1
 #define OS_STIMER_SIZE 1

 #define OS_TTIMERS 1
 #define OS_TTIMER_SIZE 1
 #define OS_ENABLE_CRITICAL_SECTION
//------------------------------------------------------------------------------
// ENABLE CONSTANTS
//------------------------------------------------------------------------------

#define OS_ENABLE_TTIMERS           // Enable task timers (OS_Delay and OS_xxx_Wait_TO)


#define OS_TASKS_ADDRESS        0x120   // Address of Task Descriptors array

//by me
#define OS_SMSG_TYPE    short
//end by me

#endif