
_CNC_INITIALIZE:

;APP.c,10 :: 		PUBLIC void CNC_INITIALIZE(void)
;APP.c,12 :: 		HWI_TIMERS_INTITALIZE();
	CALL        _HWI_TIMERS_INTITALIZE+0, 0
;APP.c,13 :: 		HWI_STEPPER_INITIALIZE();
	CALL        _HWI_STEPPER_INITIALIZE+0, 0
;APP.c,14 :: 		STEPPER_INITIALIZE();
	CALL        _STEPPER_INITIALIZE+0, 0
;APP.c,15 :: 		MECHANISM_INITIALIZE();
	CALL        _MECHANISM_INITIALIZE+0, 0
;APP.c,16 :: 		}
L_end_CNC_INITIALIZE:
	RETURN      0
; end of _CNC_INITIALIZE

_CNC_MANAGE:

;APP.c,18 :: 		PUBLIC void CNC_MANAGE(void)
;APP.c,20 :: 		MECHANISM_CALIBRATE(0);
	CLRF        FARG_MECHANISM_CALIBRATE_MechanismId+0 
	CALL        _MECHANISM_CALIBRATE+0, 0
;APP.c,21 :: 		MECHANISM_MOVE(0,150); //15 cm
	CLRF        FARG_MECHANISM_MOVE_MechanismId+0 
	MOVLW       150
	MOVWF       FARG_MECHANISM_MOVE_Distance+0 
	CALL        _MECHANISM_MOVE+0, 0
;APP.c,22 :: 		MECHANISM_CALIBRATE(1);
	MOVLW       1
	MOVWF       FARG_MECHANISM_CALIBRATE_MechanismId+0 
	CALL        _MECHANISM_CALIBRATE+0, 0
;APP.c,23 :: 		MECHANISM_MOVE(1,200); // 20 cm
	MOVLW       1
	MOVWF       FARG_MECHANISM_MOVE_MechanismId+0 
	MOVLW       200
	MOVWF       FARG_MECHANISM_MOVE_Distance+0 
	CALL        _MECHANISM_MOVE+0, 0
;APP.c,24 :: 		}
L_end_CNC_MANAGE:
	RETURN      0
; end of _CNC_MANAGE
